rutranslate={
    'The Cities Game': 'Города',
    'COLLECTION OF TERMINAL GAMES': 'КОЛЛЕКЦИЯ ТЕРМИНАЛЬНЫХ ИГР',
    'Choose a game or parameter: ': 'Выберите игру или параметр: ',
    'Enter the word: ': 'Введите слово: ',
    'Error!!!': 'Ошибка!!!',
    'Game Over!!!': 'Игра окончена!!!',
    'This word has already been used!!!': 'Это слово уже было использовано!!!',
    'You have': 'У вас есть',
    '❤️ . Enter the word: ': '❤️ . Введите слово: ',
    '❤️ . Enter the word or ability: ': '❤️ . Введите слово или способность: ',
    'You received': 'Вы получили',
    'points.': 'баллов.',
    'Absolute Champion!!!  🏆': 'Абсолютный чемпион!!!   🏆',
    'Loser!!!': 'Неудачник!!!',
    'Creator: Abdyrahym Begenjov': 'Создатель: Абдырахым Бегенджов',
    'Enter to start game: ': 'Нажмите, чтобы начать игру: ',
    'Loading...': 'Загрузка...',
    'You must enter the word!!!': 'Вы должны ввести слово!!!',
    'Enter to exit: ': 'Введите для выхода: ',
    'Enter your name: ': 'Введите свое имя: ',
    'Enter to exit mode: ': 'Войдите в режим выхода: ',
    'Game      Rules      Highscores      Exit': 'Игра      Правилы      Рекорды      Выход',
    'Choose a game mode: ': 'Выберите режим игры: ',
    'Do you want to change parameters (Enter \"Name\" or \"Language\")?: ': 'Хотите ли вы изменить параметры (введите \"Имя\" или \"Язык\")?: ',
    'Do you want to exit (\"Yes\" or \"No\")?: ': 'Вы хотите завершить (\"Да\" или \"Нет\")?: ',
    'Goodbye!!!': 'До свидания!!!',
    'Name:': 'Имя:',
    'Language:': 'Язык:',
    'Name': 'Имя',
    'Language': 'Язык',
    'No': 'Нет',
    'Game': 'Игра',
    'Rules': 'Правилы',
    'Highscores': 'Рекорды',
    'Settings': 'Настройки',
    'Exit': 'Выход',
    'NAME |': 'ИМЯ |',
    'POINTS': 'БАЛЛЫ',
    'LEADERBOARD:': 'ЛИДЕРБОРД:',
    'You are ABSOLUTE CHAMPION!!!': 'Вы АБСОЛЮТНЫЙ ЧЕМПИОН!!!',
    'You\'ve broken a new highscore!!!': 'Вы побили новый рекорд!!!',
    'WINNER': 'ПОБЕДИТЕЛЬ',
    'ROUND-UP': 'ВТОРОЕ МЕСТО',
    'BRONZE MEDALIST': 'БРОНЗОВЫЙ ПРИЗЁР',
    'LOSER': 'ЛУЗЕР',
    'This name is already taken!!!': 'Это имя уже занято!!!',
    'The name must not exceed 16 characters!!!': 'Имя не должно превышать 16 символов!!!',
    'Easy': 'Лёгкий',
    'Normal': 'Нормальный',
    'Hard': 'Сложный',
    'Player 2': 'Игрок 2',
    'Player 3': 'Игрок 3',
    'Player 4': 'Игрок 4',
    'Moment of Truth  🥁': 'Момент истины  🥁',
    'Enter number of the players: ': 'Введите количество игроков: ',
    'Parameters of game: Easy (10), Normal (20), Hard (30)': 'Параметры игры: Лёгкий (10), Нормальный (20), Сложный (30)',
    'Enter the parameter of game: ': 'Введите параметр игры: ',
    'Infinity': 'Бесконечность',
    'Party': 'Вечеринка',
    'Overall Result': 'Общий Результат',
    'Points:': 'Баллы:',
    'You have received the maximum points.': 'Вы получили максимальные очки.',
    'You are WINNER!!!': 'Вы ПОБЕДИТЕЛЬ!!!',
    'You are eliminated from the game!!!': 'Вы выбываете из игры!!!',
    'Infinity          Party': 'Бесконечность          Вечеринка',
    'Enter name: ': 'Введите имя: ',
    'Enter language: ': 'Введите язык: ',
    'Blaster': 'Бластер',
    'Game Pass': 'Пропуск',
    'Replacement': 'Замена',
    'PASS': 'ПРОПУСК',
    'BLASTER  🔫': 'БЛАСТЕР  🔫',
    'Who do you want to use the blaster on?: ': 'На кого вы хотите использовать бластер?: ',
    'Don\'t write your name!!!': 'Не пишите свое имя!!!',
    'This player is out. Choose another one.': 'Этот игрок выбыл. Выберите другого.',
    'NO': 'НЕТ',
    'GAME PASS  🦘': 'ПРОПУСК НА ИГРУ  🦘',
    'REPLACEMENT  🦝': 'ЗАМЕНА  🦝',
    'There are no suitable cities!!!': 'Подходящих городов нет!!!',
    'You don\'t get anything because you took the last place.': 'Вы ничего не получаете, т.к вы заняли последнее место.',
    'Since you didn\'t use any abilities, you get double points.': 'Поскольку вы не использовали никаких способностей, вы получаете двойные очки.',
    'You all lost because none of you scored any points.': 'Вы все проиграли, т.к никто из вас не набрал никаких баллов.',
    'Rock, Scissors, Paper': 'Камень, Ножницы, Бумага',
    'How many wins are we playing to?: ': 'До скольких побед играем?: ',
    'Rock': 'Камень',
    'Scissors': 'Ножницы',
    'Paper': 'Бумага',
    'Computer:': 'Компьютер:',
    'User:': 'Пользователь:',
    'Game Over!!!': 'Игра окончена!!!',
    'You win!!!': 'Вы победили!!!',
    'Computer wins': 'Компьютер побеждает',
    'Victories': 'Победы',
    'Defeats': 'Поражения',
    'The number must not be less than or equal to zero!!!': 'Число не должно быть меньше или равной нулю!!!',
    'Regular word:': 'Правильное слово:',
    'Enter a letter: ': 'Введите букву: ',
    'Hangman': 'Виселица',
    'This letter is already in the hidden word.': 'Эта буква уже есть в загаданном слове.',
    'You must enter the letter!!!': 'Вы должны ввести букву!!!',
    'COMPUTER1': 'КОМПЬЮТЕР1',
    'COMPUTER2': 'КОМПЬЮТЕР2',
    'COMPUTER3': 'КОМПЬЮТЕР3',
    'Snakes and Ladders': 'Змеи и Лестницы',
    'Snakes And Ladders': 'Змеи И Лестницы',
    'Parameters of game: Easy (50), Normal (75), Hard (100)': 'Параметры игры: Лёгкий (50), Нормальный (75), Сложный (100)',
    'Enter: ': 'Введите: ',
    'First Winner': 'Первый победитель',
    'Second Winner': 'Второй победитель',
    'Third Winner': 'Третий победитель',
    'Forth Winner': 'Четвертый победитель',
    'teleport': 'телепортация',
    'TELEPORTATION 🌀': 'ТЕЛЕПОРТАЦИЯ 🌀',
    'Choose player for teleportation: ': 'Выберите игрока для телепортации: ',
    'double': 'удвоение',
    'DOUBLE ✖️': 'УДВОЙНОЕ ✖️',
    'rocket': 'ракета',
    'ROCKET   +10 🚀': 'РАКЕТА   +10 🚀',
    'ICE 🧊': 'ЛЁД 🧊',
    'ice': 'лёд',
    'Choose player to freeze: ': 'Выберите игрока для заморозки: ',
    'ICE:': 'ЛЁД:',
    'Generate: ': 'Сгенерировать: ',
    'Number is bigger than parameter': 'Число больше параметра',
    'Long': 'Длинная',
    'Dangerous': 'Опасная',
    'is frozen!': 'заморожен!',
    'Let\'s Go!!!': 'Начнём!!!',
    'Steps:': 'Шаги:',
    'Position:': 'Позиция:',
    'You cannot use the \"Rocket\" as this action will take you beyond the finish line!!!': 'Нельзя использовать "Ракету", т.к этим действием вы выходите за границу финиша.',
    'Quiz': 'Викторина',
    'Timer      Infinity': 'Таймер      Бесконечность',
    'Timer': 'Таймер',
    'Infinity': 'Бесконечность',
    'Parameters of game: Easy (15), Normal (25), Hard (40), Dangerous (40 with surprise)': 'Параметры игры: Лёгкий (15), Нормальный (25), Сложный (40), Опасный (40 с сюрпризом)',
    'You have': 'У вас есть',
    'Time: ': 'Время: ',
    'Time: ': 'Время: ',
    'Enter the variant of answer: ': 'Введите вариант ответа: ',
    'You must enter the variant!!!': 'Вы должны ввести вариант!!!',
    'Regular: ': 'Правильные: ',
    'Irregular: ': 'Неправильные: ',
    'You Win!!!': 'Вы выиграли!!!',
    'Good Work!!!': 'Хорошая работа!!!',
    'Weak, but still you\'re great!!!': 'Слабовато, но все же ты молодец!!!',
    'The final question to determine the outcome of the game.': 'Последний вопрос, который определит исход игры.', 
    'Time: 00:00. Game Over!!!': 'Время: 00:00. Игра окончена!!!',
    'Game': 'Игра',
    'Dangerous': 'Опасный',
    'You are ABSOLUTE CHAMPION!!!': 'Вы АБСОЛЮТНЫЙ ЧЕМПИОН!!!',
    'YES': 'ДА',
    '💣 BOOM!!!': '💣 БУМ!!!'
             }


entranslate={j: i for i, j in rutranslate.items()}


def translator(word, language):
    match language:
        case 'en':
            return word
        case 'en1':
            if word not in entranslate:
                return 'Error!!!'
            return entranslate[word]
        case 'ru':
            if word not in rutranslate:
                return word
            return rutranslate[word]
        case _:
            return '???'